### ISSUE TITLE
Download books details as csv

### ISSUE THREAD

**Issue by arpit456jain** [vikasdo/Book-Recommendation-Analysis#105]
Download books details as csv like this

https://user-images.githubusercontent.com/55352601/116418571-e7d53f00-a859-11eb-8f8f-c2a58e50b48c.mp4

I would like to make a PR for this

**Comment by Akshay6890** [comment]
> Download books details as csv like this
> 
>  download.books.mp4 
> I would like to make a PR for this

instead of just downloading all the books, it would be good to use filters such as author name, date etc.

**Comment by arpit456jain** [comment]
> > Download books details as csv like this
> > download.books.mp4
> > I would like to make a PR for this
> 
> instead of just downloading all the books, it would be good to use filters such as author name, date etc.

Please elaborate a little bit

**Comment by Akshay6890** [comment]
> > > Download books details as csv like this
> > > download.books.mp4
> > > I would like to make a PR for this
> > 
> > 
> > instead of just downloading all the books, it would be good to use filters such as author name, date etc.
> 
> Please elaborate a little bit

When downloading a csv file, you will be having info right? So, instead of directly downloading all the info, we can give admin an option to download only certain info based on some filters such as , admin can select what are the attributes based on which he want to filter data, then in the next step he will provide the values to those attributes, for example, if admin wants books of only a particular author, then he will select name attribute as a filter and type in the name of the author, if the admin has more filters such as he wants books of a author but between certain years, then he will choose name, start date and end date filters and provide values for them.
![image](https://user-images.githubusercontent.com/47181903/116521593-c7f15a00-a8f1-11eb-9f7d-e0d9ffe7f549.png)

**Comment by Akshay6890** [comment]
> > > > Download books details as csv like this
> > > > download.books.mp4
> > > > I would like to make a PR for this
> > > 
> > > 
> > > instead of just downloading all the books, it would be good to use filters such as author name, date etc.
> > 
> > 
> > Please elaborate a little bit
> 
> When downloading a csv file, you will be having info right? So, instead of directly downloading all the info, we can give admin an option to download only certain info based on some filters such as , admin can select what are the attributes based on which he want to filter data, then in the next step he will provide the values to those attributes, for example, if admin wants books of only a particular author, then he will select name attribute as a filter and type in the name of the author, if the admin has more filters such as he wants books of a author but between certain years, then he will choose name, start date and end date filters and provide values for them.
> ![image](https://user-images.githubusercontent.com/47181903/116521593-c7f15a00-a8f1-11eb-9f7d-e0d9ffe7f549.png)

can u see the filters in image?

**Comment by arpit456jain** [comment]
currently this is beyond my skills , i can try to it , may be in future i will create a issue for that , but currently not possible for me

**Comment by Akshay6890** [comment]
> currently this is beyond my skills , i can try to it , may be in future i will create a issue for that , but currently not possible for me

ok

**Comment by Akshay6890** [comment]
> currently this is beyond my skills , i can try to it , may be in future i will create a issue for that , but currently not possible for me

Create a PR then.
